### PR TITLE
Use new etcd client module

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
This new 3.5.0 module now brings to order whole go modules story of etcd
client imports.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by kron4eg** [comment]
@xmudrii it wants to see this change:

```diff
diff --git pkg/clusterstatus/etcdstatus/etcdstatus.go pkg/clusterstatus/etcdstatus/etcdstatus.go
index 8baff43..721748f 100644
--- pkg/clusterstatus/etcdstatus/etcdstatus.go
+++ pkg/clusterstatus/etcdstatus/etcdstatus.go
@@ -24,7 +24,7 @@ import (
        "strconv"

        "github.com/pkg/errors"
-       "go.etcd.io/etcd/client/v3"
+       clientv3 "go.etcd.io/etcd/client/v3"

        kubeoneapi "k8c.io/kubeone/pkg/apis/kubeone"
        "k8c.io/kubeone/pkg/etcdutil"
```

**Comment by kron4eg** [comment]
@xmudrii please lgtm it again, had to push linter fix

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
