### PR TITLE
Helm addons

### LINKED ISSUE #2398: Write a proposal for supporting Helm charts as KubeOne addons
We should come up with a proposal (at least an informal one) for supporting Helm charts as KubeOne addons. The proposal should at least answer the following questions:

* Do we want to use Helm to deploy core components such as CNI plugins and CSI drivers? Is that possible at all and how that would look like?
* Do we want to allow users to provide their own Helm charts to be deployed by KubeOne (e.g. deploy some of their applications)?
* Do we want to allow users to override Helm charts used by KubeOne with their own Helm charts?
* Do we want to allow users to customize `values.yaml`?

Additionally, the proposal should show:

* How we can integrate Helm in KubeOne? Do we want to call it over SSH? Do we want to integrate it as a library?
  * We can see how is that done in KKP as an inspiration
* How could the API look like for interacting with Helm charts (e.g. how to provide values, enable Helm charts -- an example for each supported operation)?

We should consider the following when writing a proposal:

* KKP has a feature called Applications which is based on Helm. We should use it as an inspiration
* There's a proposal for managing CNI addons via Helm charts in KKP. We should try to follow the same approach as KKP for this

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2398

**What type of PR is this?**
/kind design

**Special notes for your reviewer**:
helm libs imports are provided just for demonstration purposes, and will be deleted prior merge

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
helm addons proposal
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — COMMENTED** [review]
Was randomly going through this, looks great :D

**Comment by kron4eg** [comment]
/assign @xmudrii 

PTAL

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⭐

**Review by xmudrii — COMMENTED** [review]
Retroactively,
/lgtm
/approve

**Pull request merged**
