### PR TITLE
[release/v1.6] Fix Flatcar torcx issues

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
This is a manual cherry-pick of the #3040 and #3043
Plus OSM version update

**What type of PR is this?**
/kind regression

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix Flatcar torcx issues
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by embik — APPROVED** [review]

**Comment by kron4eg** [comment]
cc @kubermatic/sig-release-managers

**Pull request merged**
