### PR TITLE
Update GCP CSI driver to v1.8.0

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR updates the GCP CSI driver to v1.8.0 and external-snapshotter (for GCP CSI) to v6.1.0.

**Which issue(s) this PR fixes**:
xref #2406 

**What type of PR is this?**

/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update the GCP CSI driver to v1.8.0 and external-snapshotter (for GCP CSI) to v6.1.0
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
for testing

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⚡

**Pull request merged**
