### PR TITLE
Use CentOS8 AMIs

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
A way to utilize CentOS8 on AWS.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
CentOS8 on AWS
```

/hold
until https://github.com/kubermatic/machine-controller/pull/793 is released and upgraded here

### CODE REVIEW

**Comment by xmudrii** [comment]
@kron4eg This looks good to me, but it's not going to work until there's new MC release with CentOS 8 support.

**Comment by kron4eg** [comment]
> @kron4eg This looks good to me, but it's not going to work until there's no new MC release with CentOS 8 support.

yeah, that's why I've put it on hold with comment
> until kubermatic/machine-controller#793 is released and upgraded here

**Comment by xmudrii** [comment]
> yeah, that's why I've put it on hold with comment

haven't seen it, but you're right

**Pull request merged**
