### PR TITLE
Add rsync on CentOS and Amazon Linux

### PR DESCRIPTION
**Pull request by chrkl**
Rsync was installed on Ubuntu, but not CentOS and Amazon Linux

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
@chrkl Can you please update the test fixtures? You can do it by running `go test ./... -update` from the `pkg` directory.

**Review by kron4eg — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
