### PR TITLE
Allow node resources in examples/terraform/vsphere to be changed by variables

### PR DESCRIPTION
**Pull request by eqrx**
**What this PR does / why we need it**:
Makes is easier to install KubeOne within vsphere without running OOM

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Increased vsphere template resource definitions
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@eqrx sorry, those settings a default for our tight E2E cluster so we have to keep them low, so I can not accept this. Of course you are free to modify it locally as long as you want.

P.S.
Can I propose to replace this change with "terraform vars", with default values are set to what we have now?

**Comment by kron4eg** [comment]
/hold

to avoid any accidents

**Comment by eqrx** [comment]
@kron4eg vars sounds good. will work on that

**Comment by eqrx** [comment]
Changed to variables :)

**Comment by kron4eg** [comment]
thanks!

**Pull request merged**
