### PR TITLE
Validate that IP addresses for ControlPlane and StaticWorkers are different

### LINKED ISSUE #2632: Disallow using same machines for both control plane and static workers
### Description of the feature you would like to add / User story

KubeOne considers the following config as "valid":

```yaml
...
controlPlane:
  hosts:
    - publicAddress: '192.168.1.2'
      privateAddress: '192.168.1.2'

staticWorkers:
  hosts:
    - publicAddress: '192.168.1.2'
      privateAddress: '192.168.1.2'
```

Such a config cannot produce a working cluster, as you can't reuse the same machine for both a control plane and a static worker. Instead, you can untaint the control plane node and schedule all the workload there.

### Solution details

- KubeOne validation should reject such a config

### PR DESCRIPTION
**Pull request by kron4eg**
**Which issue(s) this PR fixes**:
Fixes #2632

**What type of PR is this?**
/kind api-change

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Validate that IP addresses for ControlPlane and StaticWorkers are different
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
@kron4eg What if we add public and private addresses, and hostnames, of CP and static worker nodes to two different sets, and then compare sets? That seems like a great way to prevent any possible combination of what can go wrong, as long as we find any intersection, we error out.

**Comment by kron4eg** [comment]
> @kron4eg What if we add public and private addresses, and hostnames, of CP and static worker nodes to two different sets, and then compare sets? That seems like a great way to prevent any possible combination of what can go wrong, as long as we find any intersection, we error out.

Hostnames are optional and may be absent at the time when validation is running. That's why I didn't included them in the check. Given nested for loop almost exactly the same as sets but without fancy APIs/functions, except one thing. It point to the exact index of the problematic static worker with with .Index() function. Which is not possible with sets.

**Comment by xmudrii** [comment]
> Hostnames are optional and may be absent at the time when validation is running. That's why I didn't included them in the check.

That's true, but if we know them, it's useful to do the validation, and with sets this is very easy.

> Given nested for loop almost exactly the same as sets but without fancy APIs/functions, except one thing.

They don't function the exactly same, for example, you might "hack" around by inverting public and private addresses. This and some other cases are much easier to catch by doing the intersection.

> It point to the exact index of the problematic static worker with with .Index() function. Which is not possible with sets.

This is nice, but IMO it's also enough just to point out to what value is conflicting and you can do that with intersect.

**Comment by kron4eg** [comment]
TBH I don't want to change the thing "just because" with loosing some of the info. There has to be a good reason for that and I don't see sets as one.

**Comment by xmudrii** [comment]
@kron4eg Can we at least include the information what's the conflicting IP address? I find that much more valuable compared to the index.

**Comment by kron4eg** [comment]
> @kron4eg Can we at least include the information what's the conflicting IP address? I find that much more valuable compared to the index.

sure, and as a bonus optional validation on the hostname (excluding empty case).

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/release-note-edit
```release-note
[ACTION REQUIRED] KubeOne is now validating that IP addresses and hostnames provided for control plane nodes and static worker nodes are different. In other words, it's not possible to use the same machine both as a control plane node and a static worker node. This behavior has never been supported by KubeOne; if you want a control plane node that can schedule any pod, you can provision it as a control plane node and remove the control plane taint (`node-role.kubernetes.io/control-plane:NoSchedule`).
```

**Pull request merged**
