### PR TITLE
Make credentials file take precedence over environment.

### LINKED ISSUE #2798: Credentials file should take precedence over environment variables
### What happened?

During the provisioning of a cluster with KubeOne, the creation of the initial MachineDeployment failed with:
```
INFO[14:53:41 CEST] Creating worker machines...                  
WARN[14:53:41 CEST] KubeOne will not manage MachineDeployments objects besides initially creating them and optionally upgrading them... 
WARN[14:53:41 CEST] For more info about MachineDeployments see: https://docs.kubermatic.com/kubeone/v1.6/guides/machine-controller/ 
WARN[14:53:41 CEST] Task failed, error was: kubernetes: creating *v1alpha1.MachineDeployment kube-system/kubeone-eu-west-3a
admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: validation failed: failed to validate ami: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: REQUEST-ID
WARN[14:53:51 CEST] Retrying task...  
```

It turned out, that KubeOne used the short-living AWS credentials exposed via environment variables instead of the long-living credentials passed via the credentials file.

### Expected behavior

Credentials specified in the credentials file take precedence over the environment variables.

### How to reproduce the issue?

Follow the [Creating a Kubernetes cluster](https://docs.kubermatic.com/kubeone/v1.6/tutorials/creating-clusters/) for AWS and additionally pass a credentials file.

```bash
export AWS_ACCESS_KEY_ID="AWS_ACCESS_KEY_ID_A"
export AWS_SECRET_ACCESS_KEY="AWS_SECRET_ACCESS_KEY_A"

terraform apply
terraform output -json > outputs.json

kubeone apply -m kubeone.yaml -c credentials.yaml -t outputs.json
kubeone kubeconfig -m kubeone.yaml -c credentials.yaml -t outputs.json > kubeconfig

kubectl --kubeconfig=kubeconfig -n kube-system get secrets kubeone-machine-controller-credentials -o go-template='{{ .data.AWS_ACCESS_KEY_ID | base64decode }}'
> AWS_ACCESS_KEY_ID_A

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
kubeone apply -m kubeone.yaml -c credentials.yaml -t outputs.json
kubectl --kubeconfig=kubeconfig -n kube-system get secrets kubeone-machine-controller-credentials -o go-template='{{ .data.AWS_ACCESS_KEY_ID | base64decode }}'
> AWS_ACCESS_KEY_ID_B
```

### What KubeOne version are you using?

<details>

```yaml
{
  "kubeone": {
    "major": "1",
    "minor": "6",
    "gitVersion": "1.6.2",
    "gitCommit": "184adc3b7d0c1e2e7630ded518cbfdfab7300755",
    "gitTreeState": "",
    "buildDate": "2023-04-14T11:20:23Z",
    "goVersion": "go1.19.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "56",
    "gitVersion": "v1.56.2",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

</details>

### Provide your KubeOneCluster manifest here (if applicable)

<details>
<summary>kubeone.yaml</summary>

```yaml
apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: kubeone
versions:
  kubernetes: v1.26.4
cloudProvider:
  aws: {}
```
</details>

<details>
<summary>credentials.yaml</summary>

```yaml
AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_B"
AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_B"
```
</details>

### What cloud provider are you running on?

AWS

### What operating system are you running in your cluster?

Ubuntu 20.04/22.04

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
This PR aligns what docs says with the we already have: credentials file take precedence over environment. In addition it's also:

* added unit-tests

Supersedes #2881

**Which issue(s) this PR fixes**:
Fixes #2798

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
[ACTION REQUIRED] Credentials defined in the credentials file now have precedence over credentials defined via environment variables. This change is made to match the behavior that's already documented in the KubeOne docs. If you use both the credentials file and the environment variables, we recommend double-checking your credentials file to make sure the credentials are up to date, as those credentials will be applied on the next `kubeone apply` run
```

**Documentation**:

```documentation
NONE
```

Marking this as none, because the docs ALREADY says it's like this.

### CODE REVIEW

**Comment by xmudrii** [comment]
I'd make the release note action required because this is a _kind of_ breaking change. What do you think about something like this:
```
[ACTION REQUIRED] Credentials defined in the credentials file now have precedence over credentials defined via environment variables. This change is made to match the behavior that's already documented in the KubeOne docs. If you use both the credentials file and the environment variables, we recommend double-checking your credentials file to make sure the credentials are up to date, as those credentials will be applied on the next `kubeone apply` run
```

Otherwise, this change LGTM!

**Comment by kron4eg** [comment]
> I'd make the release note action required because this is a _kind of_ breaking change. What do you think about something like this:
> 
> ```
> [ACTION REQUIRED] Credentials defined in the credentials file now have precedence over credentials defined via environment variables. This change is made to match the behavior that's already documented in the KubeOne docs. If you use both the credentials file and the environment variables, we recommend double-checking your credentials file to make sure the credentials are up to date, as those credentials will be applied on the next `kubeone apply` run
> ```
> 
> Otherwise, this change LGTM!

Funny thing is our docs states that credentials file will prevail :D 

https://docs.kubermatic.com/kubeone/v1.7/guides/credentials/#credentials-file

>It has the priority over the environment variables, so you can use it if you want to use different credentials or if you don’t want to export credentials as environment variables.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
