### PR TITLE
Update machinecontroller to v1.17.2

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
To include hetzner "image" field

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update machinecontroller to v1.17.2
```

### CODE REVIEW

**Comment by kron4eg** [comment]
/hold

to be added terraform changes

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
