### PR TITLE
Add build options to the Makefile

### PR DESCRIPTION
**Pull request by eqrx**
The path is trimmed from binaries to make builds more reproducible.
Disable lazy binding and make global offset table read only to
harden binary a bit.

**What this PR does / why we need it**:
Enhances security of builds and makes them more reproducible.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
AFAIK trimpath can be used without actual path. And it’s Go 1.13 only. If we’re ok with this then lgtm.

**Comment by xmudrii** [comment]
> AFAIK trimpath can be used without actual path. And it’s Go 1.13 only. If we’re ok with this then lgtm.
I'm okay with this. If Go 1.13 is a problem, you can always use `go install` and `go build` manually.

**Comment by xmudrii** [comment]
/hold
I want to confirm something first

**Comment by eqrx** [comment]
Have changed the Makefile to use -trimpath without arguments. Thanks for noticing

**Comment by eqrx** [comment]
@kron4eg yeah well, the build system cannot cope with that since its <1.13 ... should we upgrade here?

**Comment by xmudrii** [comment]
This is blocked until we don't fully switch to Go 1.13.

**Pull request merged**
