### PR TITLE
Update OpenStack CCM and Cinder CSI

### PR DESCRIPTION
**Pull request by xmudrii**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

* Add support for OpenStack CCM v1.24.0 (for Kubernetes 1.24 clusters)
* Add support for OpenStack Cinder CSI driver v1.24.0 (for Kubernetes 1.24 clusters)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
xref #2011

**Does this PR introduce a user-facing change?**:
```release-note
Add support for OpenStack CCM v1.24.0 (for Kubernetes 1.24 clusters)
Add support for OpenStack Cinder CSI driver v1.24.0 (for Kubernetes 1.24 clusters)
```

/assign @kron4eg

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/approve

**Comment by WeirdMachine** [comment]
I think some parts for the snapshotter are missing. xref: https://github.com/kubermatic/kubermatic/pull/9893

**Comment by xmudrii** [comment]
@WeirdMachine They are missing, but this is going to be handled in a different PR since other providers are (potentially) affected as well. See #2051 for more details.

**Comment by WeirdMachine** [comment]
/unhold

@xmudrii sure you are already aware, my bad :)

**Pull request merged**
