### PR TITLE
Update hcloud-cloud-controller-manager image in hertzner.go

### PR DESCRIPTION
**Pull request by cebor**
**What this PR does / why we need it**:
Updates hcloud-cloud-controller-manager image in hertzner.go.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — CHANGES_REQUESTED** [review]
Can you update the reference here: https://github.com/kubermatic/kubeone/blob/56d768ef0d3df39637fa9bf9ed12686b16294013/hack/image-loader.sh#L113

**Comment by cebor** [comment]
@xmudrii done.

Can we now use a reference in the template?

**Comment by kron4eg** [comment]
OK, while we didn't merged this the new release has arrived :) https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/tag/v1.8.1

**Comment by cebor** [comment]
Updated to 1.8.1

**Comment by xmudrii** [comment]
@cebor The diff still shows 1.18.0 for me, for some reason.

**Comment by cebor** [comment]
Oops, forgot to add the files before committing.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
