### PR TITLE
Fix openstack CCM

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
E2E testing revealed some issues to be fixed:
* missing label k8s-app
* value: "true" of the toleration key
* wrong CLOUD_CONFIG file name

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix openstack CCM
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@kron4eg can you please make the release note a bit more descriptive? Just "Fix openstack CCM" is not enough.

**Comment by xmudrii** [comment]
/release-note-edit
```release-note
- Update machine-controller to v1.57.3
- Update operating-system-manager to v1.3.2
- Apply external CCM addon before applying user-provided addons
```

**Pull request merged**
