### PR TITLE
Fix kubeone setup on Hetzner

### PR DESCRIPTION
**Pull request by ThWoywod**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes Control-Plane setup issue. 
Sometimes the following issue ocure:
```
[10.10.0.6] Reading package lists...
[10.10.0.6] E: Could not get lock /var/lib/apt/lists/lock. It is held by process 1125 (apt-get)
[10.10.0.6] E: Unable to lock directory /var/lib/apt/lists/
time="11:16:15 UTC" level=error msg="ssh: installing kubeadm\nssh: popen\nProcess exited with status 100" 
```

This happen because any `apt-get update` process is still running in the background and the process is frozen. Even during a retry the `apt-get update` process is on hold.

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

### CODE REVIEW

**Comment by embik** [comment]
Hey @ThWoywod, thank you for your submission. I'll let others voice their opinion on this but I find this change a bit scary - how can we make sure this is a "frozen" apt process we're killing and not a legitimate one? What does "frozen" even mean in the first place? `apt` puts these locks in place because messing with packages while `apt` is working can be highly destructive.

I think it would be more suited to figure out why apt processes freeze for you instead of this workaround, but again, that's a personal opinion and not necessarily that of other KubeOne folks.

**Comment by kron4eg** [comment]
Sometimes unattended-upgrades gets too fast & furious, and run in your way. I'm also against killing apt in general. That problem should not be solved at kubeone level.

**Comment by ThWoywod** [comment]
Hey @embik,
thank you for your feedback. I totaly agree with you that this is quite a hacky way around. 
I invest some time to figure out why this only sometime happen but did not really get it. 

For me it is not really clear why there should be an update process running in the background. But the fact is that it does. My guess is that this happens when an installation error occurs and the retry is executed. The retry does not make sure that the processes are really terminated before it will start. 
Maybe there is also the right point to make sure that the update process has been terminated. 

I am open for any feedback and would like to adjust the code to fit better to the kubeoen way.

**Comment by ThWoywod** [comment]
@kron4eg you mean this is an issue with the default Hetzner `unattended-upgrades` configuration?

I mean the only unattended-upgrades stuff that is configured during the kubeone installation process is the Kubernetes DeamonSet and the setup of this Kubernetes Ressources should be done after the setup of the controle-plane nodes.

**Comment by kron4eg** [comment]
Yeah, hetzner integrated unattended-upgrades in the base ubuntu image and sometimes it kicks in right after the VM boot (and before kubeone).

**Comment by ThWoywod** [comment]
@kron4eg How about we stop the process of unattended-upgrades before the kubernetes installation steps are executed?

**Comment by kron4eg** [comment]
@ThWoywod well, this can be done in a custom OSP. See more at https://docs.kubermatic.com/operatingsystemmanager/guides/customize-operating-system-profile/

**Comment by xmudrii** [comment]
@ThWoywod Is it an option for you to provide cloud-init script to disable or reconfigure unattended-upgrades? You can do that [using Terraform](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#user_data) as well.

**Comment by ThWoywod** [comment]
Yeah i gess the OSP are not really the way to go because its an issue with the controle plane nodes not the machine deployment nodes.

Well yes @xmudrii this is a good suggestion. I will experiment with it a bit but at the end the kubeone code need to have an change. Disableing unattended-upgrades in generall does not sound practicable for me.

I will get back as soon as I have found a solution to the problem.

**Pull request closed without merging**
