### PR TITLE
Status logging

### PR DESCRIPTION
**Pull request by s-spindler**
**What this PR does / why we need it**:
Sorry but I just had to fix the message regarding the progress after reading it several times a day in the past days...

Regarding the ellipsis ligature: I know this is to some degree a matter of personal preference. I'm not a fan of it as it distracts my eyes from the code. It's just weird to see those special characters sprinkled around. Also, if I were to add a new log statement with ellipsis I would have to go and copy one from somewhere else since I have no idea how to type one out on my keyboard.
Lastly, if your terminal doesn't support unicode they will print some mush instead of the ellipses.

There are some cool code fonts that present ellipsis (and some special characters) as ligatures, e.g. [FiraCode](https://github.com/tonsky/FiraCode).

**Special notes for your reviewer**:
I can easily pop off the commit that changes the ellipses. Let me know what you think.

**Does this PR introduce a user-facing change?**: no

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@xmudrii PTAL

**Review by xmudrii — APPROVED** [review]
/approve

**Comment by kron4eg** [comment]
Thanks @s-spindler!

**Pull request merged**
