### PR TITLE
update Terraform examples to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This ensures all examples use Ubuntu 24.04.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update all Terraform examples to use Ubuntu version 24.04 (Noble Numbat).
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pull-kubeone-e2e-vsphere-default-install-containerd-external-v1.30

vSphere networking is down atm.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/release-note-edit
```release-note
[ACTION REQUIRED] All example Terraform configurations are using Ubuntu 24.04 instead of 22.04 by default. If you use the latest example Terraform configurations with an existing cluster, make sure to adjust the operating system as needed, otherwise your instances might get recreated by Terraform
```

**Pull request merged**
