### PR TITLE
Fix that install subcommand requires credentials for none provider

### PR DESCRIPTION
**Pull request by eqrx**
**What this PR does / why we need it**:
Fix that install subcommand requires credentials for none provider.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold

I want to check something

**Comment by xmudrii** [comment]
We validate and deploy credentials in two cases:
* If machine-controller is deployed (`.machineController.deploy` is set to `true`)
* If external CCM is deployed (`.provider.external` is set to `true`)

When deploying the external CCM, there are two bugs:
1) Validation is going to check for credentials, but as the provider name is `none`, the validation is going to fail
2) In a case when `.machineController.Deploy` is `false`, but `.provider.Name` is a provider that we don't deploy CCM for, the validation is going to fail as well. This is not expected as we don't deploy credentials, so we don't need them. This case is currently very rare and might only happen if someone tries to deploy external CCM for providers like AWS.

The machine-controller case is tricky. If we don't deploy machine-controller (and we don't deploy external CCM), we should just not check for credentials, as we don't need the credentials. If this is the case you're encountering, I think we should just change the validation rule instead. However, I was not able to reproduce this case locally, so if you share the config you used, maybe I can check is it really related to this. :slightly_smiling_face: 

Another case is that if you want to deploy machine-controller but with `.provider.Name` and `.machineController.Provider` set to `none`. My opinion is that we should still reject that, but if there are requests and good use cases, I'm okay with changing this. The problem with this case is that if `.machineController.Provider` is `none`, it's not going to deploy credentials, causing:

* Machines not to be created, although machines are going to be created as soon as the credentials are deployed,
* The user has to manually deploy the secret with credentials, but also change the machine-controller deployment to create a binding to the secret

This PR is going to allow this and the question is do we want to allow this case to happen? If we do, I would like to see a log message or a document explaining what the user should do and what is going to happen.

**Comment by eqrx** [comment]
I used the ansible example for that. Check out the branch [ansible](https://github.com/kubermatic/kubeone/tree/ansible) and just run the install playbook. kubeone will explode before anything real happens :)

If we a stuck a little bit longer with that.... is there are workaround for this since I need it to work on wednesday

**Comment by eqrx** [comment]
Error was on my side

**Pull request closed without merging**
