### PR TITLE
Bump OSM and machine-controller to latest versions

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
Since AMI issues has been fixed, we may get rid of having specific AMI

**Comment by ahmedwaleedmalik** [comment]
I forgot about this PR. We don't need this anymore, I'll bump OSM and MC in separate/new PR when we have them ready ;)

**Pull request closed without merging**
