### PR TITLE
Fix vsphere name

### PR DESCRIPTION
**Pull request by kron4eg**
Fixes a typo in vSphere name

```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
As per [DigitalOcean status page](https://do.co/status), there are API issues which are causing flakes. I'll retry testing once the issue is resolved.

**Comment by kron4eg** [comment]
as changes are not related to any of DO parts:

/override pull-kubeone-e2e-digitalocean-conformance-1.13.5
/override pull-kubeone-e2e-digitalocean-upgrade-1.13.5-1.14.0

**Pull request merged**
