### PR TITLE
Allow to automatically read terraform state from directory

### LINKED ISSUE #421: Read terraform outputs directly from terraform state file (if it's accessible)
State file is not always accessible (since state could be configured to remote), but when it does it already contains outputs and we can ready it directly. 

When state configured to some remote, old `terraform output -json` should be used.

### PR DESCRIPTION
**Pull request by eqrx**
**What this PR does / why we need it**:
Solves #421

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #421

**Special notes for your reviewer**:

**Documentation**:
None

**Release note**:
```release-note
Terraform state can now be read from stdin, file or be collected from a directory
```

### CODE REVIEW

**Comment by kron4eg** [comment]
/assign @xmudrii 

PTAL

**Comment by kron4eg** [comment]
@eqrx probably some log message is needed. Something like "exec terraform output".

**Comment by kron4eg** [comment]
I've testes this with
```
$ kubeone install config.yaml -t .
$ kubeone reset config.yaml -t .
```

works quite good!

**Comment by eqrx** [comment]
I could include the output, should I just write it to stdout or use some logger?

**Comment by kron4eg** [comment]
oh, the output should be output only when `-v` flag is used (Verbose).

**Comment by eqrx** [comment]
Should I pass the logger down to loadClusterConfig then?

**Comment by kron4eg** [comment]
`Context.Logger` it is

**Comment by xmudrii** [comment]
Looks great to me :100: As @kron4eg mentioned, it would be nice to add some output, but besides that lgtm.

**Comment by eqrx** [comment]
util.Context is created after that function runs and is not available :(

**Comment by kron4eg** [comment]
@eqrx then... call logger creation before running terraform output :)

**Comment by eqrx** [comment]
@kron4eg alright :D on it

**Pull request merged**
