### PR TITLE
Stop defaulting kube-api endpoint

### LINKED ISSUE #1848: Consider removing defaulting for the API endpoint
**What happened**:

Some providers don't provide the IP address of the API server LB on the first `terraform apply` run. If there's no API server LB in the Terraform state, and the user runs `kubeone apply`, KubeOne will default the API endpoint to the first node (even if there's LB created). Such a cluster is not an HA cluster, and the user should be aware of that.

**What is the expected behavior**:

The API endpoint should not be defaulted. KubeOne should throw an error if the API endpoint is missing. If users want to use the first (or any other) node as the Load Balancer, they should explicitly provide its IP address as a way of confirming their intentions.

**How to reproduce the issue**:

See #1847

**Anything else we need to know?**

Changing the API endpoint once the cluster is created is not an option, because it's considered to be risky, as it might break the cluster.

### PR DESCRIPTION
**Pull request by kron4eg**
**Which issue(s) this PR fixes**:
Fixes #1848

**What type of PR is this?**
/kind api-change

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Stop defaulting kube-api endpoint
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xmudrii — CHANGES_REQUESTED** [review]
We should have a migration for this change, i.e. `kubeone config migrate` should apply this migration.

**Comment by kron4eg** [comment]
blocked by #3248 to get the migration framework

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
