### PR TITLE
Canal & Calico CNI update

### PR DESCRIPTION
**Pull request by kron4eg**
**Which issue(s) this PR fixes**:

xref #2998

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
* Updated canal CNI to v3.27.2
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
Keep running into this stupid

```
cloudprovider.go:313: error testing service endpoint: Get "http://a17a57ac736ad422fa21676a04682f68-306574691.eu-west-1.elb.amazonaws.com/": dial tcp: lookup a17a57ac736ad422fa21676a04682f68-306574691.eu-west-1.elb.amazonaws.com on 169.254.20.10:53: no such host
```

/retest

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
