### PR TITLE
Update Equinix Metal CCM to v3.4.3

### PR DESCRIPTION
**Pull request by xmudrii**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Update Equinix Metal CCM to v3.4.3.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
xref #2011

**Does this PR introduce a user-facing change?**:
```release-note
Update Equinix Metal CCM to v3.4.3
```

### CODE REVIEW

**Comment by xmudrii** [comment]
I already manually tested this PR and it seems to work as expected. This includes running this PR on a cluster created with KubeOne v1.4.5.

**Comment by xmudrii** [comment]
/hold
to let #2183 go in first.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
