### PR TITLE
chore: update aws variables to include type of value

### PR DESCRIPTION
**Pull request by nerdeveloper**
Signed-off-by: nerdeveloper <obinna@kubermatic.io>

**What this PR does / why we need it**:
update type of value for the resources, this will serve as type check for values when they are modified

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
N/A
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
/retest

@nerdeveloper in order to get this merged, you'll have to edit the PR description and add a release-note.

**Review by kron4eg — APPROVED** [review]
/approve

**Comment by nerdeveloper** [comment]
Thank you @kron4eg I have just updated and added a release note

**Pull request merged**
