### PR TITLE
[Test] Run cluster provisioning and upgrading tests on Azure

### PR DESCRIPTION
**Pull request by kron4eg**
Relevant to #2243 and #2249

### CODE REVIEW

**Comment by kron4eg** [comment]
## v1.24.3

### Containerd (OSM)

Ubuntu: 
/test pull-kubeone-e2e-azure-default-install-containerd-v1.24.3

### Containerd (no OSM)

Ubuntu: 
/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-v1.24.3

### External CCM (OSM)

Ubuntu: 
/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.24.3

### External CCM (no OSM)

Ubuntu: 
/test pull-kubeone-e2e-azure-default-legacy-machine-controller-containerd-external-v1.24.3

**Comment by xmudrii** [comment]
Sonobuoy got stuck for some reason in `pull-kubeone-e2e-azure-default-upgrade-docker-from-v1.22.12-to-v1.23.9`, but all tests passed, so I'm considering that job as passed.

**Comment by xmudrii** [comment]
/override pull-kubeone-e2e-azure-rockylinux-upgrade-containerd-from-v1.23.9-to-v1.24.3

**Comment by xmudrii** [comment]
/override pull-kubeone-e2e-azure-rhel-legacy-machine-controller-containerd-v1.24.3

**Pull request closed without merging**
