### PR TITLE
Upgrade to cilium v1.12.2

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:

Upgrade to cilium v1.12.2.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

This is a pre-requisite for https://github.com/kubermatic/kubeone/issues/2223

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Upgrade to cilium v1.12.2
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Something seems broken, I'll try to reproduce this locally.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
@ahmedwaleedmalik It's expected that the Cilium job fails. Some conformance tests are failing, but that's a known issue in Cilium. See the following tickets for more details:

* https://github.com/cilium/cilium/issues/14287#issuecomment-1192288840
* https://github.com/cilium/cilium/issues/12116

We can't do much about that besides eventually skipping those tests.

That said...
/override pull-kubeone-e2e-aws-default-cilium-containerd-v1.22.12

**Pull request merged**
