### PR TITLE
WIP Add missing terraform examples for ubuntu 24.04 

### PR DESCRIPTION
**Pull request by SimonTheLeg**
_WIP because not all providers are finished. No draft PR so we can run E2E tests. No need to review as of now_

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:

- [x] I noticed that Azure will not let us use the sku `server` with the current VMs that we have chosen. Error is
 Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The selected VM size 'Standard_F2' cannot boot Hypervisor Generation '2'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '2' VM Size. For more information, see https://aka.ms/azuregen2vm". Do we want to use `server-gen1` or do we want to upgrade to a hypervisor gen 2 VM? -> upgrade to gen 2 VM
- [ ] Is there anything that needs to be done for Nutanix, VMWare cloud director?

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```
Release not already added in the original PR.

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by SimonTheLeg** [comment]
/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.30.1

Hmm the Azure test seems to run into IP Address limitations. So let's run one at a time to see if the issue persists

```
Error: creating/updating Public Ip Address: (Name "k1-1818230726840029184-cp-0" / Resource Group "k1-1818230726840029184-rg"): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="StaticPublicIPCountLimitReached" Message="Cannot create more than 20 public IP addresses with static allocation method for this subscription in this region." Details=[]
```

**Comment by SimonTheLeg** [comment]
/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.30.1

just to make sure it was not the azure outage yesterday that broke it

**Comment by SimonTheLeg** [comment]
/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.30.1

re-trigger for some live debugging

**Comment by SimonTheLeg** [comment]
/test pull-kubeone-e2e-azure-default-install-containerd-external-v1.30.1

worker nodes were stuck trying to join the cluster beforehand. Rebased with main to first see if bumping machine-controller already fixes this issue

**Comment by SimonTheLeg** [comment]
sorry I never got to finish this. There is some issue with the Azure tests. All the other changed providers worked. GH does not list them in the checks, but if you run the tests [from here](https://github.com/kubermatic/kubeone/pull/3308#issuecomment-2258007452), all except Azure will work.

With regards to Azure: I checked in the portal and the machines were successfully created, but they are unable to join the cluster. Machine controller logs 

```
{"level":"info","time":"2024-07-19T13:17:56.632Z","logger":"machineset-controller","caller":"machineset/controller.go:254","msg":"Too few replicas, creating more","machineset":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d","spec":2,"current":0,"diff":2}
{"level":"info","time":"2024-07-19T13:17:56.632Z","logger":"machineset-controller","caller":"machineset/controller.go:259","msg":"Creating new machine","machineset":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d","spec":2,"current":0,"index":1}
{"level":"info","time":"2024-07-19T13:17:56.685Z","logger":"machineset-controller","caller":"machineset/controller.go:259","msg":"Creating new machine","machineset":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d","spec":2,"current":0,"index":2}
{"level":"error","time":"2024-07-19T13:17:57.089Z","logger":"machine-controller","caller":"machine/controller.go:817","msg":"cloud-init configuration: cloud config is not ready yet","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure","secret":"bootstrap"}
{"level":"info","time":"2024-07-19T13:18:02.669Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:198","msg":"Creating public IP","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure","name":"k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk-netiface-pubip"}
{"level":"info","time":"2024-07-19T13:18:04.348Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:232","msg":"Fetching info for IP address","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure","name":"k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk-netiface-pubip"}
{"level":"info","time":"2024-07-19T13:18:04.710Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:380","msg":"Creating/Updating public network interface","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure","interface":"k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk-netiface"}
{"level":"info","time":"2024-07-19T13:18:05.374Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:396","msg":"Fetching info about network interface","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure","interface":"k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk-netiface"}
{"level":"info","time":"2024-07-19T13:18:05.474Z","logger":"machine-controller","caller":"azure/provider.go:710","msg":"Creating machine","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure"}
{"level":"info","time":"2024-07-19T13:18:52.509Z","logger":"machine-controller","caller":"machine/controller.go:839","msg":"Created machine at cloud provider","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure"}
{"level":"info","time":"2024-07-19T13:18:55.836Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:198","msg":"Creating public IP","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure","name":"k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m-netiface-pubip"}
{"level":"info","time":"2024-07-19T13:18:57.516Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:232","msg":"Fetching info for IP address","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure","name":"k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m-netiface-pubip"}
{"level":"info","time":"2024-07-19T13:18:57.943Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:380","msg":"Creating/Updating public network interface","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure","interface":"k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m-netiface"}
{"level":"info","time":"2024-07-19T13:18:58.607Z","logger":"machine-controller","caller":"azure/create_delete_resources.go:396","msg":"Fetching info about network interface","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure","interface":"k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m-netiface"}
{"level":"info","time":"2024-07-19T13:18:58.699Z","logger":"machine-controller","caller":"azure/provider.go:710","msg":"Creating machine","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure"}
{"level":"info","time":"2024-07-19T13:19:45.487Z","logger":"machine-controller","caller":"machine/controller.go:839","msg":"Created machine at cloud provider","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-fhz4m","provider":"azure"}
E0719 13:28:14.068443       1 leaderelection.go:340] Failed to update lock optimitically: etcdserver: request timed out, possibly due to previous leader failure, falling back to slow path
{"level":"info","time":"2024-07-19T13:32:59.372Z","logger":"machine-controller","caller":"machine/controller.go:946","msg":"Join cluster timeout expired for machine; deleting ittimeout15m0s","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure"}
{"level":"info","time":"2024-07-19T13:32:59.399Z","logger":"machine-controller","caller":"azure/provider.go:763","msg":"Deleting VM","machine":"kube-system/k1-1814285281495355392-pool1-56ff7ccf9d-lg6qk","provider":"azure"}
```

Hope this info already helps a bit, I am unsure if I can return to this topic with the current workload.

**Comment by xmudrii** [comment]
@SimonTheLeg @kron4eg I've been debugging this issue on Friday and discovered that cloud-init is not working properly on MC/OSM-managed nodes. Apparently, Azure changed something in cloud-init and the way we use it in OSM doesn't work any longer. I don't have any logs handy, but I'll try to reproduce the issue again and will follow up in the OSM repo.

**Comment by xmudrii** [comment]
I'll be taking over this PR, thanks a lot @SimonTheLeg for getting started!
/close

**Pull request closed without merging**
