### PR TITLE
Allow upstream cluster autoscaler flags configuration

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
This PR is to allow the configuration of the upstream cluster-autoscaler supported flags via KubeOne provided cluster-autoscaler addon to address https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#my-cluster-is-below-minimum--above-maximum-number-of-nodes-but-ca-did-not-fix-that-why and https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#im-running-cluster-with-nodes-in-multiple-zones-for-ha-purposes-is-that-supported-by-cluster-autoscaler issue as faced at the one of the customer end. 

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Allow the configuration of the upstream cluster-autoscaler flags  `--enforce-node-group-min-size` and `--balance-similar-node-groups`
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@archups it's not a bug it's a feature :joy: 

/approve
/lgtm

**Comment by archups** [comment]
> @archups it's not a bug it's a feature 😂
> 
> /approve /lgtm

Oops, I was confused whether to add as feature or bug..  Thanks @kron4eg  for the clarification and review. :)

**Pull request merged**
