### PR TITLE
[release/v1.7] Update MC to v1.57.6

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Update machine-controller to v1.57.6.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update machine-controller to v1.57.6
```

**Documentation**:

```documentation
NONE
```

/cc @kron4eg

### CODE REVIEW

**Comment by kron4eg** [comment]
cc @kubermatic/sig-release-managers

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
