### PR TITLE
Initialize host.Labels to avoid NPE

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
Fixes NPE found during pre-release testing

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Initialize host.Labels to avoid NPE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by kron4eg** [comment]
manual testing doesn't show any failures

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
