### PR TITLE
Run gofmt for hack/tools.go

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR runs gofmt for `hack/tools.go`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @kron4eg

### CODE REVIEW

**Comment by kron4eg** [comment]
heh, I see why it wasn't caught previously by linter

` golangci-lint run ./pkg/... ./test/... ` 🔥

**Comment by xmudrii** [comment]
@kron4eg What would happen if we used `golangci-lint run ./...` (or `golangci-lint run` which is equivalent to the former command) instead? Would it include vendor too maybe?

**Comment by kron4eg** [comment]
I suppose this is leftover since dark times when we had vendor :D

**Comment by xmudrii** [comment]
Oh, right, we don't have `vendor` anymore. :man_shrugging: I'll update the PR to include all packages for lint.

**Comment by xmudrii** [comment]
@kron4eg Updated the PR.

**Comment by xmudrii** [comment]
@kron4eg Reverted the change of linter settings.

**Pull request merged**
