### PR TITLE
Switch to quay.io from docker.io for calico images

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Switching to `quay.io` from `docker.io` for the following images:
- calico/cni
- calico/kube-controllers
- calico/node

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Switching to quay.io from docker.io for calico cni, kube-controllers, and node images.
```

### CODE REVIEW

**Comment by kron4eg** [comment]
please also move to quay.io addons/calico-vxlan images, example:

https://github.com/kubermatic/kubeone/blob/f062a8cb68196a639bb5042f14b38b9fb64539df/addons/calico-vxlan/calico-vxlan.yaml#L4204

**Comment by ahmedwaleedmalik** [comment]
> please also move to quay.io addons/calico-vxlan images, example:

Done but wouldn't it be better to declare these images https://github.com/kubermatic/kubeone/blob/master/pkg/templates/images/images.go#L168 here as well? Or just assume that the ones already declared should be consumed for calico-vxlan addon.

**Comment by xmudrii** [comment]
@ahmedwaleedmalik We can do that, but if we would do that, I wouldn't use the same images/keys. Instead, I would add new keys for Calico VXLAN. There are two reasons for that:

* Someone might forget to update the Calico VXLAN manifest (e.g. not knowing about it), which could break something for Calico VXLAN users
* We might want to intentionally use different Calico versions for Canal and Calico VXLAN

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik We can do that, but if we would do that, I wouldn't use the same images/keys. Instead, I would add new keys for Calico VXLAN. There are two reasons for that:
> 
> * Someone might forget to update the Calico VXLAN manifest (e.g. not knowing about it), which could break something for Calico VXLAN users
> * We might want to intentionally use different Calico versions for Canal and Calico VXLAN

Very valid point, that makes sense. I have updated this accordingly PTAL.

**Comment by xmudrii** [comment]
/lgtm
/assign @kron4eg 
for approval

**Pull request merged**
