### PR TITLE
Patch/value types

### PR DESCRIPTION
**Pull request by nerdeveloper**
**What this PR does / why we need it**:
Strictly set the value types in the examples folder for different cloud providers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nerdeveloper** [comment]
@kron4eg any idea why my test fails? this happened in my previous PR

**Comment by kron4eg** [comment]
@nerdeveloper yeah, because of Go’s map randomized iteration, please rerun it.

**Review by kron4eg — APPROVED** [review]
/approve

**Pull request merged**
