### PR TITLE
Fix flatcar torcx issues

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
Update to the latest OSM release, that includes fix for flatcar torcx worker issue

**Which issue(s) this PR fixes**:
Worker node companion for #3040

**What type of PR is this?**
/kind regression

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update OSM image to fix the flatcar torcx issue
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by embik** [comment]
Looks like something is broken on the (static?) nodes for `pull-kubeone-e2e-aws-flatcar-install-containerd-external-v1.27.7`:

```
time="14:00:14 UTC" level=info msg="Running host probes..."
time="14:00:14 UTC" level=error msg="containerd version was: \"\": Invalid Semantic Version" node=172.31.186.232
time="14:00:14 UTC" level=error msg="containerd version was: \"\": Invalid Semantic Version" node=172.31.186.206
time="14:00:14 UTC" level=error msg="containerd version was: \"\": Invalid Semantic Version" node=172.31.187.16
```

**Review by embik — APPROVED** [review]

**Pull request merged**
