### PR TITLE
Upgrade digitalocean CCM to v0.1.15

### PR DESCRIPTION
**Pull request by kron4eg**
```release-note
Upgrade digitalocean CCM to v0.1.15
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@xmudrii technically we could continue to use that `--cloud-controller=digitalocean` flag, and nothing would be changed (because according to release notes it's like that by default), but yeah, it's better to remove it to not forget about it later. So, it's removed now.

**Comment by xmudrii** [comment]
/test pull-kubeone-e2e-digitalocean-conformance-1.15
/hold
Unhold once DO test is green

**Comment by kron4eg** [comment]
/hold cancel

`pull-kubeone-e2e-digitalocean-conformance-1.15 — Job succeeded.`

**Pull request merged**
