### PR TITLE
Update cilium to v1.15

### PR DESCRIPTION
**Pull request by kron4eg**
**Which issue(s) this PR fixes**:

xref #2998

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update cilium to v1.15
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
Still dns failures

/retest

**Comment by kron4eg** [comment]
```
    helpers.go:621: some e2e tests failed:
        [
          {
            "name": "[It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]",
            "status": "failed",
            "details": {}
          },
          {
            "name": "[It] [sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]",
            "status": "failed",
            "details": {}
          },
          {
            "name": "[It] [sig-network] Services should serve endpoints on same port and different protocols [Conformance]",
            "status": "failed",
            "details": {}
          }
        ]
```

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
