### PR TITLE
Remove usage of template_file in aws-dualstack Terraform scripts

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR removes the usage of `template_file` in Terraform scripts for `aws-dualstack`. The `template_file` provider has been replaced with the built-in `templatefile` function. The old `template_file` provider has been deprecated and it doesn't have binaries for `darwin_arm64` (Mac M1).

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/hold
There's one more bug.

**Pull request merged**
