### PR TITLE
Fix terraform consistent variables for machine deployment replicas

### PR DESCRIPTION
**Pull request by adeniyistephen**
**What type of PR is this?**
Fixing terraform variables for consistency among cloud providers
/kind feature

**What this PR does / why we need it**:
To enable consistent variables among cloud providers for the machine deployment replicas.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/ps-team-flotilla/issues/99 ticket 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
BREAKING: hetzner terraform config rename variable `workers_replicas` to `initial_machinedeployment_replicas`
```

### CODE REVIEW

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]
Can you please document this new variable in the respective `README.md` files for the cloud providers as well? For example, https://github.com/kubermatic/kubeone/blob/master/examples/terraform/aws/README.md#L69

**Comment by kron4eg** [comment]
@adeniyistephen please add a release note (in the PR description) about breaking change in hetzner terraform config.
As of updating READMEs like @ahmedwaleedmalik said please leave that along for now. I'll update them later by myself and add some automation to update.

**Comment by adeniyistephen** [comment]
Done.

**Pull request merged**
